### ISSUE TITLE
HEADS UP: CREATED NEW master BRANCH

### ISSUE THREAD

**Issue by janl** [hoodiehq/hoodie-plugin-users#28]
In roder to get the rewrite branch into `master`, I move the master branch to `1.0.0` and then pushed the rewrite branch + additional dbs + travis as master. Good luck! :)

**Comment by Charlotteis** [comment]
Cheers @janl. As it's been almost a year (oh, how time flies!) since this was done, I feel confident that I can close this. Thanks! :tada:
