### ISSUE TITLE
Errors when opening Users tab in Admin:

### ISSUE THREAD

**Issue by idanb11** [hoodiehq/hoodie-plugin-users#37]
`GET http://127.0.0.1:6005/_api/_plugins/_assets/styles/admin-dashboard-uikit.css  404`
`GET http://127.0.0.1:6005/_api/_plugins/_assets/scripts/admin-dashboard-uikit.js  404`
`Uncaught ReferenceError: jQuery is not defined`
`Uncaught ReferenceError: Backbone is not defined`

Please help resolving this issue...

**Comment by zoepage** [comment]
@espy could you please take a look? <3

**Comment by espy** [comment]
Hello @idanb11, I just tried to replicate you problem, all I did was 
`````
$ hoodie new appname
$ cd appname
$ hoodie start
````
and the admin panels load the files you're missing here and in https://github.com/hoodiehq/hoodie-plugin-appconfig/issues/6 without any trouble.

Is your setup any different than this?

**Comment by idanb11** [comment]
Off course my setup is different.
I created my Hoodie app and I install it in the following way:
-  Install all Hood.ie dependencies
- Install AngularJS plugin, 
- Install Bower
- run $ npm install
- run $ bower install
- Start Hood.ie server

One note: I installed the same Hoodie app on our QA server and on that server i didn't have any problems with the Users tab in the Admin dashboard...

Should I try to install the Hoodie app again and see if i get the same errors.

**Comment by espy** [comment]
Your local machine might be missing some `hoodie-server` dependencies, although I'm not sure how that would happen. Could you check whether your local hoodie project has `/node_modules/hoodie-server/node_modules/hoodie-admin-dashboard-uikit`? That's where the files you're missing should come from. If they're missing, maybe delete `node_modules` and `npm install` again.

You can also try adding `-v` to your hoodie commands in the terminal for more verbose output. 

I'll also forward this to the rest of the team to see if anyone has any ideas. Sorry for the trouble!

**Comment by idanb11** [comment]
Hi @espy  
the folder you mentioned `/node_modules/hoodie-server/node_modules/hoodie-admin-dashboard-uikit` exist on my machine.
Using the -v when running `$ hoodie start` doesn't produce anything special.

I just updated all Hoodie dependencies version and still this problem exist...

**Comment by jayhogan** [comment]
I'm having the exact same issue with the Users tab. I've tried deleting the node_modules folder, re-creating the app, nothing seems to work. I am using version 0.6.3 (node v0.10.29, npm 2.6.1, platform: darwin) on Mac OSX.

I'm also getting a 401 on calls to http://127.0.0.1:6002/_api/plugins/_changes?include_docs=true&since=0.

Any ideas?

**Comment by idanb11** [comment]
Hi @jayhogan 
Still didn't find a way to fix this.

**Comment by miguelangelorocha** [comment]
cd node_modules/hoodie-plugin-users/
bower install
vim admin-dashboard/index.html

<!DOCTYPE html>




<html class="no-js"> 
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>Users</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width">
        <link rel="icon" href="images/favicon_128.png">
        
        <link rel="stylesheet" href="/_api/_plugins/_assets/styles/admin-dashboard-uikit.css">
        <link rel="stylesheet" href="styles/app.css">
    </head>
    <body>
        <script src="/_api/_plugins/_assets/scripts/admin-dashboard-uikit.js"></script>
        <script src="scripts/plugins.js"></script>
        <script src="assets/vendor/underscore-min.js"></script>

        <script src="components/jquery-timeago/jquery.timeago.js"></script>
        <script src="components/handlebars/handlebars.runtime.js"></script>
        <script src="components/underscore/underscore.js"></script>
        <script src="components/backbone/backbone.js"></script>
        <script src="components/tablesort/tablesort.min.js"></script>
        <script src="components/backbone.subroute/backbone.subroute.js"></script>
        <script src="components/layoutmanager/backbone.layoutmanager.js"></script>

        
        <script src="scripts/app.js"></script>
    </body>
</html>

cd ../..

hoodie start -v

**Comment by idanb11** [comment]
@miguelangelorocha Thanks.

:+1:
