### ISSUE TITLE
Pls help with this error: - Cannot read property 'hooks' of undefined

### ISSUE THREAD

**Issue by idanb11** [hoodiehq/hoodie-plugin-users#91]
Starting Plugin: 'hoodie-plugin-appconfig'
Starting Plugin: 'hoodie-plugin-email'
Starting Plugin: 'hoodie-plugin-users'
Starting Plugin: 'hoodie-plugin-angularjs'
All plugins started.

TypeError: Cannot read property 'hooks' of undefined
    at exports.confirmUser (/home/apps/d8r8r/node_modules/hoodie-plugin-users/lib/signup.js:70:13)
    at /home/apps/d8r8r/node_modules/async/lib/async.js:1080:20
    at iterate (/home/apps/d8r8r/node_modules/async/lib/async.js:146:13)
    at /home/apps/d8r8r/node_modules/async/lib/async.js:157:25
    at exports.createAdditionalDBs (/home/apps/d8r8r/node_modules/hoodie-plugin-users/lib/signup.js:55:5)
    at /home/apps/d8r8r/node_modules/async/lib/async.js:1080:20
    at iterate (/home/apps/d8r8r/node_modules/async/lib/async.js:146:13)
    at /home/apps/d8r8r/node_modules/async/lib/async.js:157:25
    at /home/apps/d8r8r/node_modules/hoodie-plugins-api/lib/databases.js:113:16
    at /home/apps/d8r8r/node_modules/hoodie-plugins-api/node_modules/async/lib/async.js:226:13

Stopping CouchDB...

**Comment by varjmes** [comment]
Hi @idanb11!

This is the function that is upset: https://github.com/hoodiehq/hoodie-plugin-users/blob/next/lib/signup.js#L70

How are you calling the `confirmUser` function in your own code? It seems that the problem may be in the callback you provided. Without being able to see how you're using it, I can't offer much guidance.

Have a great day ✨

**Comment by idanb11** [comment]
I actually don't call the `confirmUser` function.

But for now this error is gone.

Thanks. @Charlotteis
